# Generated by Django 4.2.7 on 2024-03-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0025_remove_message_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gullyapp.createteam'),
        ),
    ]
