# Generated by Django 4.2.7 on 2024-03-03 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0027_clan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='name',
        ),
        migrations.AddField(
            model_name='clan',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clan', to='gullyapp.createteam'),
        ),
    ]
