# Generated by Django 4.2.7 on 2024-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0024_room_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
