# Generated by Django 4.2.7 on 2024-03-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0026_userprofile_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_leader', to='gullyapp.createteam')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gullyapp.createteam')),
            ],
        ),
    ]
