# Generated by Django 4.2.7 on 2024-03-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0028_remove_clan_leader_remove_clan_name_clan_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gullyapp.createteam'),
        ),
        migrations.DeleteModel(
            name='clan',
        ),
    ]
